[build]
  command = "docker build -t ooptimo-dashboard ."
  publish = "."

[build.environment]
  DOCKER_BUILDKIT = "1"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[dev]
  command = "streamlit run app.py"
  port = 8080