services:
  - type: web
    name: ooptimo-dashboard
    env: docker
    buildCommand: docker build -t ooptimo-dashboard .
    startCommand: docker run -p 8080:8080 ooptimo-dashboard
    envVars:
      - key: PORT
        value: 8080
    autoDeploy: true